ALTER DATABASE club_deportivo CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP TABLE IF EXISTS canchas;
DROP TABLE IF EXISTS socios;
DROP TABLE IF EXISTS deportes;

CREATE TABLE IF NOT EXISTS deportes (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO deportes (nombre)
VALUES 
('Fútbol'),
('Tenis'),
('Pádel');

CREATE TABLE IF NOT EXISTS socios (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(150) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS canchas (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(150) NOT NULL,
id_deporte INT NOT NULL,
precio_hora INT NOT NULL,
techada BOOLEAN NOT NULL DEFAULT FALSE,
activa BOOLEAN NOT NULL DEFAULT TRUE,
FOREIGN KEY(id_deporte) REFERENCES deportes(id)
);